### ISSUE TITLE
Test Runner Debug mode doesn't work 

### ISSUE THREAD

**Issue by heatherlp** [IBM-Blockchain/blockchain-vscode-extension#1038]
Doesn't work for me or Rieha

```
/Users/rieha.burrell@ibm.com/Work/Contracts/ts/node_modules/mocha/bin/_mocha:540
   throw err;
   ^

Error: must provide pattern
   at new GlobSync (/Users/rieha.burrell@ibm.com/Work/Contracts/ts/node_modules/mocha/node_modules/glob/sync.js:31:11)
   at Function.globSync [as sync] (/Users/rieha.burrell@ibm.com/Work/Contracts/ts/node_modules/mocha/node_modules/glob/sync.js:26:10)
   at Object.lookupFiles (/Users/rieha.burrell@ibm.com/Work/Contracts/ts/node_modules/mocha/lib/utils.js:517:20)
   at args.forEach.arg (/Users/rieha.burrell@ibm.com/Work/Contracts/ts/node_modules/mocha/bin/_mocha:531:22)
   at Array.forEach (<anonymous>)
   at Object.<anonymous> (/Users/rieha.burrell@ibm.com/Work/Contracts/ts/node_modules/mocha/bin/_mocha:528:6)
   at Module._compile (module.js:652:30)
   at Object.Module._extensions..js (module.js:663:10)
   at Module.load (module.js:565:32)
   at tryModuleLoad (module.js:505:12)
   at Function.Module._load (module.js:497:3)
   at Function.Module.runMain (module.js:693:10)
   at startup (bootstrap_node.js:191:16)
   at bootstrap_node.js:612:3
Waiting for the debugger to disconnect...
```
and it doesn't actually try and debug anything (breakpoints aren't hit)

There aren't any issues against the test runner so perhaps it's us? Needs investigation
Independent of javascript or typescript generated smart contract tests, and I get it ehen I try and debug our unit tests too, e.g. extension.test.ts

**Comment by cazfletch** [comment]
It works for me, i can debug the generated tests and set break points

**Comment by heatherlp** [comment]
false alarm 🙄
