### ISSUE TITLE
Failed to activate extension: Failed to execute command

### ISSUE THREAD

**Issue by ashishchandr70** [IBM-Blockchain/blockchain-vscode-extension#1205]
Unable to activate the IBM Blockchain extension for Hyperledger Fabric

## Description
Please see the log file below.

## Expected Behavior
The extension should be activated

## Actual Behavior
Activation errors out with the message "Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v69-linux-x64-glibc
Found: [electron-v4.1-linux-x64-glibc]

## Steps to Reproduce
1. Download/Install extension v1.0.5
2. The activation errors out.

## Existing issues
Similar issues:
1. #435 
2. #1124 

## Log File

[7/31/2019 3:34:16 PM] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

```
[7/31/2019 3:34:16 PM] [INFO] Starting IBM Blockchain Platform Extension
[7/31/2019 3:34:16 PM] [INFO] Attempting to require dependency: grpc
[7/31/2019 3:34:16 PM] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v69-linux-x64-glibc
Found: [electron-v4.1-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/src/node/extension_binary/node-v69-linux-x64-glibc/grpc_node.node'
[7/31/2019 3:34:16 PM] [INFO] Updating native node modules
[7/31/2019 3:34:16 PM] [INFO] Rebuilding native node modules
[7/31/2019 3:34:18 PM] [INFO] > grpc@1.21.1 install /root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc
[7/31/2019 3:34:18 PM] [INFO] > node-pre-gyp install --fallback-to-build --library=static_library
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp
[7/31/2019 3:34:19 PM] [INFO]  WARN Using request for node-pre-gyp https download 
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp WARN
[7/31/2019 3:34:19 PM] [INFO]  Pre-built binaries not installable for grpc@1.21.1 and electron@4.1.5 (electron-v4.1 ABI, glibc) (falling back to source compile with node-gyp) 
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp WARN Hit error getaddrinfo ENOTFOUND node-precompiled-binaries.grpc.io node-precompiled-binaries.grpc.io:443 
[7/31/2019 3:34:19 PM] [INFO] gyp WARN install got an error, rolling back install
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! configure error 
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack network settings.
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:197:21)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at emitOne (events.js:116:13)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at Request.emit (events.js:211:7)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at Request.onRequestError (/usr/local/lib/node_modules/npm/node_modules/request/request.js:881:8)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at emitOne (events.js:116:13)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at ClientRequest.emit (events.js:211:7)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:401:9)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at emitOne (events.js:116:13)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at TLSSocket.emit (events.js:211:7)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:66:8)
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! System Linux 3.10.0-957.10.1.el7.x86_64
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/src/node/extension_binary/electron-v4.1-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/src/node/extension_binary/electron-v4.1-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v4.1" "--dist-url=https://atom.io/download/electron"
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! cwd /root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! node -v v8.16.0
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! node-gyp -v v3.8.0
[7/31/2019 3:34:19 PM] [INFO] gyp ERR! not ok 
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp 
[7/31/2019 3:34:19 PM] [INFO] ERR! build error 
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR!
[7/31/2019 3:34:19 PM] [INFO]  stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/src/node/extension_binary/electron-v4.1-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/src/node/extension_binary/electron-v4.1-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.1 --dist-url=https://atom.io/download/electron' (1)
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! stack
[7/31/2019 3:34:19 PM] [INFO]      at emitTwo (events.js:126:13)
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! System
[7/31/2019 3:34:19 PM] [INFO]  Linux 3.10.0-957.10.1.el7.x86_64
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! command "/usr/local/bin/node" "/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! cwd /root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! node -v v8.16.0
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp 
[7/31/2019 3:34:19 PM] [INFO] ERR! node-pre-gyp -v v0.13.0
[7/31/2019 3:34:19 PM] [INFO] node-pre-gyp ERR! not ok 
[7/31/2019 3:34:19 PM] [INFO] Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/src/node/extension_binary/electron-v4.1-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/src/node/extension_binary/electron-v4.1-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v4.1 --dist-url=https://atom.io/download/electron' (1)
[7/31/2019 3:34:19 PM] [INFO] npm ERR! code ELIFECYCLE
[7/31/2019 3:34:19 PM] [INFO] npm ERR! errno 1
[7/31/2019 3:34:19 PM] [INFO] npm ERR! grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
[7/31/2019 3:34:19 PM] [INFO] npm ERR! Exit status 1
[7/31/2019 3:34:19 PM] [INFO] npm ERR! 
[7/31/2019 3:34:19 PM] [INFO] npm ERR! Failed at the grpc@1.21.1 install script.
[7/31/2019 3:34:19 PM] [INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[7/31/2019 3:34:19 PM] [INFO] npm ERR! A complete log of this run can be found in:
[7/31/2019 3:34:19 PM] [INFO] npm ERR!     /root/.npm/_logs/2019-07-31T19_34_19_967Z-debug.log
[7/31/2019 3:34:19 PM] [ERROR] Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=4.1.5, --runtime=electron, --dist-url=https://atom.io/download/electron, --update-binary, --fallback-to-build, --target_arch=x64" return code 1. Please ensure that you have node and npm installed
[7/31/2019 3:34:19 PM] [ERROR] Failed to activate extension: Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=4.1.5, --runtime=electron, --dist-url=https://atom.io/download/electron, --update-binary, --fallback-to-build, --target_arch=x64" return code 1

```

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.5
* Visual Studio Code version: 1.36.1
* Environment name and version : Nodejs v8.16.0, npm v6.4.1
* Operating System and version: RHEL v7.6 (Maipo)

**Comment by ashishchandr70** [comment]
I also wanted to add that we have a severely restricted network - the Linux boxes do not have internet access so everything has to be copied over and installed.

**Comment by ashishchandr70** [comment]
Ran **npm rebuild** as well on '/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/' folder and here is the log output.

It appears to be having issues with the grpc package and wants to install node-pre-gyp. Why would it do that if it is already present under ...1.0.5/node_modules/grpc/node-modules ?

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'rebuild' ]
2 info using npm@6.4.1
3 info using node@v8.16.0
4 info readInstalled object
5 verbose rebuild path, id [ '/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5',
5 verbose rebuild   'ibm-blockchain-platform@1.0.5' ]
6 verbose rebuild path, id [ '/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/@fidm/x509',
6 verbose rebuild   '@fidm/x509@1.1.3' ]
7 verbose rebuild path, id [ '/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/@fidm/asn1',
7 verbose rebuild   '@fidm/asn1@1.0.4' ]
8 verbose rebuild path, id [ '/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/tweetnacl',
8 verbose rebuild   'tweetnacl@1.0.1' ]
9 verbose rebuild path, id [ '/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/axios',
9 verbose rebuild   'axios@0.19.0' ]
10 verbose rebuild path, id [ '/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/follow-redirects',
10 verbose rebuild   'follow-redirects@1.5.10' ]
[... log deleted for brevity ...]

[ log continues]
7902 info build /root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/node_modules/yargs
7903 info lifecycle yargs@3.32.0~preinstall: yargs@3.32.0
7904 info linkStuff yargs@3.32.0
7905 silly linkStuff yargs@3.32.0 has /root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/node_modules as its parent node_modules
7906 info lifecycle yargs@3.32.0~install: yargs@3.32.0
7907 info lifecycle yargs@3.32.0~postinstall: yargs@3.32.0
7908 info lifecycle grpc@1.21.1~install: grpc@1.21.1
7909 verbose lifecycle grpc@1.21.1~install: unsafe-perm in lifecycle false
7910 verbose lifecycle grpc@1.21.1~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/node_modules/.bin:/root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/.bin:/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin
7911 verbose lifecycle grpc@1.21.1~install: CWD: /root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc
7912 silly lifecycle grpc@1.21.1~install: Args: [ '-c',
7912 silly lifecycle   'node-pre-gyp install --fallback-to-build --library=static_library' ]
7913 silly lifecycle grpc@1.21.1~install: Returned: code: 1  signal: null
7914 info lifecycle grpc@1.21.1~install: Failed to exec install script
7915 verbose stack Error: grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
7915 verbose stack Exit status 1
7915 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
7915 verbose stack     at emitTwo (events.js:126:13)
7915 verbose stack     at EventEmitter.emit (events.js:214:7)
7915 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
7915 verbose stack     at emitTwo (events.js:126:13)
7915 verbose stack     at ChildProcess.emit (events.js:214:7)
7915 verbose stack     at maybeClose (internal/child_process.js:915:16)
7915 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
7916 verbose pkgid grpc@1.21.1
7917 verbose cwd /root/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5
7918 verbose Linux 3.10.0-957.10.1.el7.x86_64
7919 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
7920 verbose node v8.16.0
7921 verbose npm  v6.4.1
7922 error code ELIFECYCLE
7923 error errno 1
7924 error grpc@1.21.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
7924 error Exit status 1
7925 error Failed at the grpc@1.21.1 install script.
7925 error This is probably not a problem with npm. There is likely additional logging output above.
7926 verbose exit [ 1, true ]

**Comment by cazfletch** [comment]
Hi @ashishchandr70, thanks for adding the part about the restricted network, that explains the problem. To make it work you will need to do two things

1. Go to `~/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5` on your file system, open the file `package.json` and find the activationEvents. Change it from `*` to the following:
```
 "onView:gatewayExplorer",
        "onView:aRuntimeOpsExplorer",
        "onView:aPackagesExplorer",
        "onView:walletExplorer",
        "onCommand:gatewaysExplorer.addGatewayEntry",
        "onCommand:gatewaysExplorer.deleteGatewayEntry",
        "onCommand:gatewaysExplorer.connectEntry",
        "onCommand:gatewaysExplorer.disconnectEntry",
        "onCommand:gatewaysExplorer.refreshEntry",
        "onCommand:gatewaysExplorer.editGatewayEntry",
        "onCommand:gatewaysExplorer.testSmartContractEntry",
        "onCommand:gatewaysExplorer.testAllSmartContractEntry",
        "onCommand:gatewaysExplorer.submitTransactionEntry",
        "onCommand:gatewaysExplorer.evaluateTransactionEntry",
        "onCommand:gatewaysExplorer.associateWallet",
        "onCommand:gatewaysExplorer.dissociateWallet",
        "onCommand:aPackagesExplorer.createSmartContractProjectEntry",
        "onCommand:aPackagesExplorer.packageSmartContractProjectEntry",
        "onCommand:aPackagesExplorer.deleteSmartContractPackageEntry",
        "onCommand:aPackagesExplorer.exportSmartContractPackageEntry",
        "onCommand:aPackagesExplorer.importSmartContractPackageEntry",
        "onCommand:aPackagesExplorer.refreshEntry",
        "onCommand:aRuntimeOpsExplorer.installSmartContractEntry",
        "onCommand:aRuntimeOpsExplorer.instantiateSmartContractEntry",
        "onCommand:aRuntimeOpsExplorer.refreshEntry",
        "onCommand:aRuntimeOpsExplorer.startFabricRuntime",
        "onCommand:aRuntimeOpsExplorer.stopFabricRuntime",
        "onCommand:aRuntimeOpsExplorer.restartFabricRuntime",
        "onCommand:aRuntimeOpsExplorer.teardownFabricRuntime",
        "onCommand:aRuntimeOpsExplorer.toggleFabricRuntimeDevMode",
        "onCommand:aRuntimeOpsExplorer.openNewTerminal",
        "onCommand:aRuntimeOpsExplorer.exportConnectionProfileEntry",
        "onCommand:aRuntimeOpsExplorer.upgradeSmartContractEntry",
        "onCommand:aRuntimeOpsExplorer.createNewIdentityEntry",
        "onCommand:walletExplorer.refreshEntry",
        "onCommand:walletExplorer.addWalletEntry",
        "onCommand:walletExplorer.addWalletIdentityEntry",
        "onCommand:walletExplorer.editWalletEntry",
        "onCommand:walletExplorer.removeWalletEntry",
        "onCommand:walletExplorer.deleteIdentityEntry",
        "onCommand:walletExplorer.exportWalletEntry",
        "onCommand:extensionHome.open",
        "onCommand:tutorialGallery.open",
        "onDebug"
```

2. Next you will need to download the pre-built grpc library, unzip it and copy it to `~/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.5/node_modules/grpc/src/node/extension_binary. You will then need to rename it to be `node-v69-linux-x64-glibc`. You can download the prebuilt binary from https://console.cloud.google.com/storage/browser/node-precompiled-binaries.grpc.io/grpc/v1.21.1?project=grpc-testing&prefix=electron. You will need the one for the correct platform using electron 4.1

**Comment by ashishchandr70** [comment]
Thanks @cazfletch for taking the time to explain. It worked perfectly and I was able to activate the extension.

**Comment by Parthimdu** [comment]
I am getting the same error in IBM platform version 1.0.8 , i am trying the above fix, whats the correct prebuilt binary? any thoughts please?

**Comment by SHIVAMGUPTA24** [comment]
[30/3/2020 5:25:00 pm] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[30/3/2020 5:25:00 pm] [INFO] Starting IBM Blockchain Platform Extension
[30/3/2020 5:25:01 pm] [INFO] Attempting to require dependency: grpc
[30/3/2020 5:25:02 pm] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v6.1-linux-x64-glibc
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc/grpc_node.node'
Require stack:
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/grpc_extension.js
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/client_interceptors.js
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/client.js
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/index.js
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/build/extension/dependencies/DependencyManager.js
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/build/extension/webview/PreReqView.js
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/build/extension/util/ExtensionUtil.js
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/build/extension/util/Reporter.js
- /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/build/extension/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
[30/3/2020 5:25:02 pm] [INFO] Updating native node modules
[30/3/2020 5:25:02 pm] [INFO] Rebuilding native node modules
[30/3/2020 5:25:05 pm] [INFO] > grpc@1.23.3 install /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc
[30/3/2020 5:25:05 pm] [INFO] > node-pre-gyp install --fallback-to-build --library=static_library
[30/3/2020 5:25:05 pm] [INFO] node-pre-gyp
[30/3/2020 5:25:05 pm] [INFO]  WARN
[30/3/2020 5:25:05 pm] [INFO]  Using request for node-pre-gyp https download 
[30/3/2020 5:25:15 pm] [INFO] node-pre-gyp
[30/3/2020 5:25:15 pm] [INFO]  WARN Pre-built binaries not installable for grpc@1.23.3 and electron@6.1.5 (electron-v6.1 ABI, glibc) (falling back to source compile with node-gyp) 
[30/3/2020 5:25:15 pm] [INFO] node-pre-gyp WARN Hit error getaddrinfo ENOTFOUND node-precompiled-binaries.grpc.io node-precompiled-binaries.grpc.io:443 
[30/3/2020 5:25:16 pm] [INFO] gyp
[30/3/2020 5:25:16 pm] [INFO]  
[30/3/2020 5:25:16 pm] [INFO] ERR! configure error 
[30/3/2020 5:25:16 pm] [INFO] gyp 
[30/3/2020 5:25:16 pm] [INFO] ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! stack     at PythonFinder.failNoPython (/home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/configure.js:484:19)
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! stack     at PythonFinder.<anonymous> (/home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/configure.js:406:16)
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! stack     at F (/home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/which/which.js:68:16)
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! stack     at E (/home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/which/which.js:80:29)
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! stack     at /home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/which/which.js:89:16
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! stack     at /home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/isexe/index.js:42:5
[30/3/2020 5:25:16 pm] [INFO] gyp ERR!
[30/3/2020 5:25:16 pm] [INFO]  stack     at /home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! System Linux 5.0.0-37-generic
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! command "/home/shivam/.nvm/versions/node/v8.16.2/bin/node" "/home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v6.1" "--dist-url=https://atom.io/download/electron"
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! cwd /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! node -v v8.16.2
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! node-gyp -v v3.8.0
[30/3/2020 5:25:16 pm] [INFO] gyp ERR! not ok 
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp
[30/3/2020 5:25:16 pm] [INFO]  ERR! build error 
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! 
[30/3/2020 5:25:16 pm] [INFO] stack Error: Failed to execute '/home/shivam/.nvm/versions/node/v8.16.2/bin/node /home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --dist-url=https://atom.io/download/electron' (1)
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! System Linux 5.0.0-37-generic
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! command "/home/shivam/.nvm/versions/node/v8.16.2/bin/node" "/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! cwd /home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! node -v v8.16.2
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! node-pre-gyp -v v0.13.0
[30/3/2020 5:25:16 pm] [INFO] node-pre-gyp ERR! not ok 
[30/3/2020 5:25:16 pm] [INFO] Failed to execute '/home/shivam/.nvm/versions/node/v8.16.2/bin/node /home/shivam/.nvm/versions/node/v8.16.2/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/node_modules/grpc/src/node/extension_binary/electron-v6.1-linux-x64-glibc --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --dist-url=https://atom.io/download/electron' (1)
[30/3/2020 5:25:16 pm] [INFO] npm
[30/3/2020 5:25:16 pm] [INFO]  ERR! code ELIFECYCLE
[30/3/2020 5:25:16 pm] [INFO] npm ERR! errno 1
[30/3/2020 5:25:16 pm] [INFO] npm 
[30/3/2020 5:25:16 pm] [INFO] ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
[30/3/2020 5:25:16 pm] [INFO] npm ERR! Exit status 1
[30/3/2020 5:25:16 pm] [INFO] npm ERR! 
[30/3/2020 5:25:16 pm] [INFO] npm ERR! Failed at the grpc@1.23.3 install script.
[30/3/2020 5:25:16 pm] [INFO] npm
[30/3/2020 5:25:16 pm] [INFO]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
[30/3/2020 5:25:16 pm] [INFO] npm 
[30/3/2020 5:25:16 pm] [INFO] ERR! A complete log of this run can be found in:
[30/3/2020 5:25:16 pm] [INFO] npm ERR!     /home/shivam/.npm/_logs/2020-03-30T11_55_16_240Z-debug.log
[30/3/2020 5:25:16 pm] [ERROR] Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed
[30/3/2020 5:25:16 pm] [ERROR] Failed to activate extension: Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
[30/3/2020 5:25:16 pm] [ERROR] Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
	at ChildProcess.<anonymous> (/home/shivam/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.16/build/extension/util/CommandUtil.js:77:39)
	at ChildProcess.emit (events.js:200:13)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
   


cant start the platform do help

**Comment by cazfletch** [comment]
Looks like you are missing python `[30/3/2020 5:25:16 pm] [INFO] ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`

**Comment by SHIVAMGUPTA24** [comment]
thank u it worked

**Comment by IykeOkey** [comment]
@cazfletch pls your reply on issue raised by @ashishchandr70 refers to linux os, but I have the same issue but it is on Mac OSX. Pls how should I solve it in my Mac machine? Thanks in anticipation.

**Comment by cazfletch** [comment]
@lykeOkey you need to post the error that you get
