### ISSUE TITLE
Extension doesn't work with wsl2 and crashes vs code

### ISSUE THREAD

**Issue by bigworld12** [IBM-Blockchain/blockchain-vscode-extension#1405]
## Description
when i open the fabric samples folder and activate the extension, i get a crash message
![image](https://user-images.githubusercontent.com/10135395/64909685-d33d4500-d70f-11e9-9ae7-c7de95415dc2.png)
![image](https://user-images.githubusercontent.com/10135395/64909706-ff58c600-d70f-11e9-85e6-31731f1a0445.png)

i tried checking the logs, this is what i found in `%AppData%\Code\logs\20190914T142946\renderer4.log`
```
[2019-09-14 16:54:30.882] [renderer4] [info] [remote-connection][ExtensionHost][9f7b5…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2019-09-14 16:54:30.882] [renderer4] [info] [remote-connection][ExtensionHost][9f7b5…][reconnect] waiting for 5 seconds before reconnecting...
[2019-09-14 16:54:35.882] [renderer4] [info] [remote-connection][ExtensionHost][9f7b5…][reconnect] resolving connection...
[2019-09-14 16:54:35.882] [renderer4] [info] [remote-connection][ExtensionHost][9f7b5…][reconnect] connecting to 192.168.191.150:43561...
[2019-09-14 16:54:35.927] [renderer4] [error] [remote-connection][ExtensionHost][9f7b5…][reconnect][192.168.191.150:43561] received error control message when negotiating connection. Error:
[2019-09-14 16:54:35.927] [renderer4] [error] Error: Connection error: Unknown reconnection token.
    at _ (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:506)
    at o.onControlMessage.l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:659)
    at d.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at v.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:350:801)
    at _receiveMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:355:324)
    at _socketDisposables.push._socketReader.onMessage.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:354:281)
    at d.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at g.acceptChunk (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:348:234)
    at _register._socket.onData.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:347:592)
    at Socket.t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:357:518)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-09-14 16:54:35.927] [renderer4] [error] [remote-connection][ExtensionHost][9f7b5…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2019-09-14 16:54:35.927] [renderer4] [error] Error: Connection error: Unknown reconnection token.
    at _ (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:506)
    at o.onControlMessage.l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:659)
    at d.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at v.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:350:801)
    at _receiveMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:355:324)
    at _socketDisposables.push._socketReader.onMessage.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:354:281)
    at d.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at g.acceptChunk (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:348:234)
    at _register._socket.onData.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:347:592)
    at Socket.t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:357:518)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-09-14 16:54:43.834] [renderer4] [info] [remote-connection][ExtensionHost][d06cb…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2019-09-14 16:54:43.834] [renderer4] [info] [remote-connection][ExtensionHost][d06cb…][reconnect] waiting for 5 seconds before reconnecting...
[2019-09-14 16:54:48.834] [renderer4] [info] [remote-connection][ExtensionHost][d06cb…][reconnect] resolving connection...
[2019-09-14 16:54:48.834] [renderer4] [info] [remote-connection][ExtensionHost][d06cb…][reconnect] connecting to 192.168.191.150:35303...
[2019-09-14 16:54:48.879] [renderer4] [error] [remote-connection][ExtensionHost][d06cb…][reconnect][192.168.191.150:35303] received error control message when negotiating connection. Error:
[2019-09-14 16:54:48.879] [renderer4] [error] Error: Connection error: Unknown reconnection token.
    at _ (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:506)
    at o.onControlMessage.l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:659)
    at d.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at v.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:350:801)
    at _receiveMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:355:324)
    at _socketDisposables.push._socketReader.onMessage.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:354:281)
    at d.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at g.acceptChunk (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:348:234)
    at _register._socket.onData.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:347:592)
    at Socket.t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:357:518)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-09-14 16:54:48.879] [renderer4] [error] [remote-connection][ExtensionHost][d06cb…][reconnect] A permanent error occurred in the reconnecting loop! Will give up now! Error:
[2019-09-14 16:54:48.879] [renderer4] [error] Error: Connection error: Unknown reconnection token.
    at _ (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1678:506)
    at o.onControlMessage.l (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1676:659)
    at d.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at v.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:350:801)
    at _receiveMessage (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:355:324)
    at _socketDisposables.push._socketReader.onMessage.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:354:281)
    at d.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:107:468)
    at g.acceptChunk (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:348:234)
    at _register._socket.onData.e (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:347:592)
    at Socket.t (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:357:518)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
[2019-09-14 16:54:53.556] [renderer4] [warning] UNRESPONSIVE extension host, 'Shan.code-settings-sync' took 72% of 5063ms, saved PROFILE here: 'C:\Users\bigowlrd12\AppData\Local\Temp\exthost-36a23b.cpuprofile' [{"id":"gc","total":9000,"percentage":0},{"id":"ms-vscode-remote.remote-wsl","total":1000,"percentage":0},{"id":"program","total":1405000,"percentage":28},{"id":"self","total":1000,"percentage":0},{"id":"Shan.code-settings-sync","total":3647000,"percentage":72}]

``` 
## Steps to Reproduce
1. Have latest vscode version
```
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18980
```
2. Have the extension installed
![image](https://user-images.githubusercontent.com/10135395/64909883-b0139500-d711-11e9-9ed5-58d85ae3bdbf.png)

3. activate the extension, the error message pops up

I am running Ubuntu on WSL 2 on windows 10.0.18980

**Comment by cazfletch** [comment]
WSL doesn’t currently work with the extension

**Comment by cazfletch** [comment]
closing as not going to support wsl
