### ISSUE TITLE
Timeout on instantiating chaincode

### ISSUE THREAD

**Issue by Alkiimista** [IBM-Blockchain/blockchain-vscode-extension#1533]
## Description
When attempting to instantiate the chaincode times out the first time, the second attempt to instantiate gives an error.

## Expected Behavior
Instantiated chaincode

## Actual Behavior
```
TypeError: Class extends value undefined is not a constructor or null

at Object.<anonymous> (/usr/local/src/dist/src/hyperledger/models/document.js:15:47)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/usr/local/src/dist/src/hyperledger/drcContract.js:4:20)
at Module._compile (module.js:653:30)

```
Local Fabric log: https://pastebin.com/DVDS5w5r
Checked for circular dependency https://i.stack.imgur.com/aOrQV.png

## Log File
Blockchain log: https://pastebin.com/qL8wXXeL

## Your Environment

* IBM Blockchain Platform Extension Version: 1.0.12
* Visual Studio Code version: 1.39.1
* Environment name and version: Node.js v10.15.2, npm v6.11.3
* Operating System and version: Ubuntu 18.04 LTS (Virtual Machine)
* Developing in TypeScript

**Comment by cazfletch** [comment]
I think this is a problem with your chaincode rather than with the extension so closing. You should ask on hyperledger fabric rocket chat if you are having problems with writing your chaincode
