### ISSUE TITLE
Error: Missing required option `file`

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/blockchain-vscode-extension#1554]
```
Error: Missing required option `file`
    at new exports.File (/Users/sstone1/git/blockchain-vscode-extension/node_modules/nconf/lib/nconf/stores/file.js:26:11)
    at exports.Provider.Provider.create (/Users/sstone1/git/blockchain-vscode-extension/node_modules/nconf/lib/nconf/provider.js:162:10)
    at exports.Provider.Provider.add (/Users/sstone1/git/blockchain-vscode-extension/node_modules/nconf/lib/nconf/provider.js:133:28)
    at exports.Provider.Provider.file (/Users/sstone1/git/blockchain-vscode-extension/node_modules/nconf/lib/nconf/provider.js:63:15)
    at Config.reorderFileStores (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/node_modules/fabric-client/lib/Config.js:71:17)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/node_modules/fabric-client/lib/Client.js:39:8)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/node_modules/fabric-client/lib/Client.js:1938:3)
    at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
    at Function.define._installInterceptor.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
    at Function.t.connectProxyResolver.t.getExtensionPathIndex.then.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/node_modules/fabric-client/index.js:25:18)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/node_modules/fabric-client/index.js:27:3)
    at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
    at Function.define._installInterceptor.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
    at Function.t.connectProxyResolver.t.getExtensionPathIndex.then.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/lib/gateway.js:9:16)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/lib/gateway.js:295:3)
    at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
    at Function.define._installInterceptor.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
    at Function.t.connectProxyResolver.t.getExtensionPathIndex.then.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/index.js:54:26)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/node_modules/fabric-network/index.js:69:3)
    at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
    at Function.define._installInterceptor.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
    at Function.t.connectProxyResolver.t.getExtensionPathIndex.then.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricWallet.js:27:26)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricWallet.js:73:3)
    at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
    at Function.define._installInterceptor.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
    at Function.t.connectProxyResolver.t.getExtensionPathIndex.then.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricWalletGenerator.js:25:24)
    at Object.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricWalletGenerator.js:41:3)
    at Module.t._initNodeRequire.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:785:720)
    at Function.define._installInterceptor.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:754:302)
    at Function.t.connectProxyResolver.t.getExtensionPathIndex.then.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:750:870)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
    at Function.createFabricWalletGenerator (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricWalletGeneratorFactory.js:19:42)
    at FabricRuntime.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricRuntime.js:85:103)
    at Generator.next (<anonymous>)
    at __awaiter (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricRuntime.js:21:71)
    at new Promise (<anonymous>)
    at __awaiter (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricRuntime.js:17:12)
    at FabricRuntime.importWalletsAndIdentities (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricRuntime.js:83:16)
    at FabricRuntimeManager.<anonymous> (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricRuntimeManager.js:74:32)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sstone1/git/blockchain-vscode-extension/build/extension/fabric/FabricRuntimeManager.js:18:58)
```

**Comment by sstone1** [comment]
This is a bug in the Fabric Node.js SDK: https://jira.hyperledger.org/browse/FABN-1402
