### ISSUE TITLE
IBP extension does not work on MacOS Catalina

### ISSUE THREAD

**Issue by lichunl** [IBM-Blockchain/blockchain-vscode-extension#1607]
## Description
After upgrade to MacOS Catalina with version 10.15.1, IBP extension can not work any more. Tried to uninstall & reinstall it again, but it didn't work.
error:
Failed to activate extension: Could not get electron verion, connect ETIMEDOUT 75.126.215.88:443
Source: IBM Blockchain Platform(extension)

After 'retry activation'
It showed below error:
Failed to activate extension: Could not get electron verion, write EPROTO 140334412117400:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:586:SSL alert number 40

## Expected Behavior
Expect IBP extension works ok

## Actual Behavior
Failed to install IBP extension, error happened

## Possible Fix
don't know

## Steps to Reproduce
1. On MacOS Catalina
2. Open VS code
3. Install IBP extension v1.0.14
4. Failed

## Log File
[1-Blockchain.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/3806991/1-Blockchain.log)

## Your Environment

* IBM Blockchain Platform Extension Version: v1.0.14
* Visual Studio Code version:1.39.2
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1): node:v10.16.3  npm:6.12.1
* Operating System and version:  MacOS Catalina with version 10.15.1
* Link to your project:

**Comment by Jakeeyturner** [comment]
Hi @lichunl,

I think you're seeing some kind of network connection problem.

The problem seems to be coming from: https://github.com/IBM-Blockchain/blockchain-vscode-extension/blob/ffbecdcc0e36dd9badd441f61e401ca8d4cdecef/extension/dependencies/DependencyManager.ts#L521

Could you verify that you can definitely reach the following url?:
`https://raw.githubusercontent.com/electron/releases/master/lite.json`

---

Searching on Google for:
```
Failed to activate extension: Could not get electron verion, write EPROTO 140334412117400:error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE:../../third_party/boringssl/src/ssl/tls_record.cc:586:SSL alert number 40
```
Also returns lots of results and suggests that it may be a connection problem.

Thanks,
Jake

**Comment by lichunl** [comment]
Thank you @Jakeeyturner !  The original issue was resolved after changing to another network connection.

But I got this error. Is this a new issue?
[3-Blockchain.log](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/3808692/3-Blockchain.log)

```
[11/5/2019 7:15:28 PM] [INFO] Initializing local runtime manager
[11/5/2019 7:15:29 PM] [ERROR] Failed to activate extension: Error: No path for wallet has been provided
[11/5/2019 7:15:29 PM] [ERROR] Error: No path for wallet has been provided
	at new FileSystemWallet (/Users/chunlingli/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.14/node_modules/fabric-network/lib/impl/wallet/filesystemwallet.js:65:10)
	at new FabricWallet (/Users/chunlingli/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.14/build/extension/fabric/FabricWallet.js:30:9)
	at FabricWalletGenerator.<anonymous> (/Users/chunlingli/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.14/build/extension/fabric/FabricWalletGenerator.js:34:20)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/chunlingli/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.14/build/extension/fabric/FabricWalletGenerator.js:18:58)

```

**Comment by Jakeeyturner** [comment]
Glad to hear it's sorted!

If you follow these instructions, then this will solve the problem - https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1593#issuecomment-548364610
This problem will be addressed in our next release later this week.

Thanks,
Jake
