### ISSUE TITLE
Cannot activate extension with latest version of studio Code

### ISSUE THREAD

**Issue by makenoisewacamayo** [IBM-Blockchain/blockchain-vscode-extension#1631]
## Description
The latest version of VSC update to Electron 6 and node 12, this is causing issue with IBM blockchain extension failed to build native extension.

## Expected Behavior
Should not fail to build native extension

## Actual Behavior
```bash
Failed to activate extension: Failed to execute command "npm" with arguments "rebuild, grpc, --target=6.1.2, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
```

## Possible Fix
Not sure how to fix, but vsc is shipped with an internal node does nothing to do node installed in your operating system, and maybe this causing the issue, include the release notes of version 1.40 October 2019.

#### Electron 6.0 Update

In this milestone, we finished the exploration of bundling Electron 6 into VS Code, making it the first time this Electron version ships with stable. This is a major Electron release and comes with Chromium 76.0.3809.146 and Node.js 12.4.0 (a major leap forward from our current version with Chromium 69 and Node.js 10.11.0).

## Steps to Reproduce

Install the latest VSC version 1.40  and the install IBM blockchain plugin for vsc.

## Log File

```
[11/12/2019 11:29:03 AM] [INFO] Starting IBM Blockchain Platform Extension
[11/12/2019 11:29:04 AM] [INFO] Attempting to require dependency: grpc
[11/12/2019 11:29:05 AM] [INFO] Error requiring dependency: Failed to load /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node. Cannot find module '/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node'
Require stack:
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/grpc_extension.js
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/client_interceptors.js
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/client.js
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/index.js
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/build/extension/dependencies/DependencyManager.js
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/build/extension/webview/PreReqView.js
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/build/extension/util/ExtensionUtil.js
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/build/extension/util/Reporter.js
- /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/build/extension/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
[11/12/2019 11:29:05 AM] [INFO] Updating native node modules
[11/12/2019 11:29:05 AM] [INFO] Rebuilding native node modules
[11/12/2019 11:29:06 AM] [INFO] > grpc@1.23.3 install /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc
[11/12/2019 11:29:06 AM] [INFO] > node-pre-gyp install --fallback-to-build --library=static_library
[11/12/2019 11:29:06 AM] [INFO] node-pre-gyp
[11/12/2019 11:29:06 AM] [INFO]  
[11/12/2019 11:29:06 AM] [INFO] WARN Using request for node-pre-gyp https download 
[11/12/2019 11:29:07 AM] [INFO] node-pre-gyp
[11/12/2019 11:29:07 AM] [INFO]  WARN Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/electron-v6.1-darwin-x64-unknown.tar.gz 
[11/12/2019 11:29:07 AM] [INFO] node-pre-gyp WARN Pre-built binaries not found for grpc@1.23.3 and electron@6.1.2 (electron-v6.1 ABI, unknown) (falling back to source compile with node-gyp) 
[11/12/2019 11:29:09 AM] [INFO] Traceback (most recent call last):
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
[11/12/2019 11:29:09 AM] [INFO]     sys.exit(gyp.script_main())
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
[11/12/2019 11:29:09 AM] [INFO]     return main(sys.argv[1:])
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
[11/12/2019 11:29:09 AM] [INFO]     return gyp_main(args)
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
[11/12/2019 11:29:09 AM] [INFO]     generator.GenerateOutput(flat_list, targets, data, params)
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
[11/12/2019 11:29:09 AM] [INFO]     part_of_all=qualified_target in needed_targets)
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
[11/12/2019 11:29:09 AM] [INFO]     self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
[11/12/2019 11:29:09 AM] [INFO]     env = self.GetSortedXcodeEnv()
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
[11/12/2019 11:29:09 AM] [INFO]     additional_settings)
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
[11/12/2019 11:29:09 AM] [INFO]     additional_settings)
[11/12/2019 11:29:09 AM] [INFO]   File "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
[11/12/2019 11:29:09 AM] [INFO]     if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
[11/12/2019 11:29:09 AM] [INFO] TypeError: '>=' not supported between instances of 'tuple' and 'str'
[11/12/2019 11:29:09 AM] [INFO] gyp
[11/12/2019 11:29:09 AM] [INFO]  
[11/12/2019 11:29:09 AM] [INFO] ERR! configure error 
[11/12/2019 11:29:09 AM] [INFO] gyp
[11/12/2019 11:29:09 AM] [INFO]  ERR! 
[11/12/2019 11:29:09 AM] [INFO] stack Error: `gyp` failed with exit code: 1
[11/12/2019 11:29:09 AM] [INFO] gyp ERR! stack
[11/12/2019 11:29:09 AM] [INFO]      at ChildProcess.onCpExit (/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
[11/12/2019 11:29:09 AM] [INFO] gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
[11/12/2019 11:29:09 AM] [INFO] gyp ERR!
[11/12/2019 11:29:09 AM] [INFO]  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[11/12/2019 11:29:09 AM] [INFO] gyp ERR!
[11/12/2019 11:29:09 AM] [INFO]  System Darwin 18.7.0
[11/12/2019 11:29:09 AM] [INFO] gyp
[11/12/2019 11:29:09 AM] [INFO]  ERR! command "/Users/nisum/.nvm/versions/node/v10.15.3/bin/node" "/Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v6.1" "--dist-url=https://atom.io/download/electron"
[11/12/2019 11:29:09 AM] [INFO] gyp ERR! cwd /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc
[11/12/2019 11:29:09 AM] [INFO] gyp ERR! node -v v10.15.3
[11/12/2019 11:29:09 AM] [INFO] gyp ERR! node-gyp -v v5.0.5
[11/12/2019 11:29:09 AM] [INFO] gyp ERR! not ok 
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp
[11/12/2019 11:29:09 AM] [INFO]  ERR! build error 
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp ERR! stack
[11/12/2019 11:29:09 AM] [INFO]  Error: Failed to execute '/Users/nisum/.nvm/versions/node/v10.15.3/bin/node /Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --dist-url=https://atom.io/download/electron' (1)
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp
[11/12/2019 11:29:09 AM] [INFO]  ERR! 
[11/12/2019 11:29:09 AM] [INFO] stack     at ChildProcess.emit (events.js:189:13)
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp 
[11/12/2019 11:29:09 AM] [INFO] ERR! 
[11/12/2019 11:29:09 AM] [INFO] stack
[11/12/2019 11:29:09 AM] [INFO]      at maybeClose (internal/child_process.js:970:16)
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp
[11/12/2019 11:29:09 AM] [INFO]  ERR! stack
[11/12/2019 11:29:09 AM] [INFO]      at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp 
[11/12/2019 11:29:09 AM] [INFO] ERR! System Darwin 18.7.0
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp ERR! command "/Users/nisum/.nvm/versions/node/v10.15.3/bin/node" "/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp 
[11/12/2019 11:29:09 AM] [INFO] ERR! cwd /Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp ERR! node -v
[11/12/2019 11:29:09 AM] [INFO]  v10.15.3
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp ERR! node-pre-gyp -v v0.13.0
[11/12/2019 11:29:09 AM] [INFO] node-pre-gyp ERR! not ok 
[11/12/2019 11:29:09 AM] [INFO] Failed to execute '/Users/nisum/.nvm/versions/node/v10.15.3/bin/node /Users/nisum/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --dist-url=https://atom.io/download/electron' (1)
[11/12/2019 11:29:09 AM] [INFO] npm
[11/12/2019 11:29:09 AM] [INFO]  ERR! code ELIFECYCLE
[11/12/2019 11:29:09 AM] [INFO] npm
[11/12/2019 11:29:09 AM] [INFO]  ERR! errno 1
[11/12/2019 11:29:09 AM] [INFO] npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
[11/12/2019 11:29:09 AM] [INFO] npm
[11/12/2019 11:29:09 AM] [INFO]  ERR! Exit status 1
[11/12/2019 11:29:09 AM] [INFO] npm
[11/12/2019 11:29:09 AM] [INFO]  ERR! 
[11/12/2019 11:29:09 AM] [INFO] npm ERR!
[11/12/2019 11:29:09 AM] [INFO]  Failed at the grpc@1.23.3 install script.
[11/12/2019 11:29:09 AM] [INFO] npm ERR!
[11/12/2019 11:29:09 AM] [INFO]  This is probably not a problem with npm. There is likely additional logging output above.
[11/12/2019 11:29:09 AM] [INFO] npm ERR! A complete log of this run can be found in:
[11/12/2019 11:29:09 AM] [INFO] npm ERR!     /Users/nisum/.npm/_logs/2019-11-12T14_29_09_551Z-debug.log
[11/12/2019 11:29:09 AM] [ERROR] Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.2, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed
[11/12/2019 11:29:09 AM] [ERROR] Failed to activate extension: Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.2, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
[11/12/2019 11:29:09 AM] [ERROR] Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.2, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
	at ChildProcess.<anonymous> (/Users/nisum/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.15/build/extension/util/CommandUtil.js:77:39)
	at ChildProcess.emit (events.js:200:13)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```
## Your Environment

* IBM Blockchain Platform Extension Version: 1.015
* Visual Studio Code version: 1.40
* Environment name and version: node v10.15.3 and npm 6.12.
* Operating System and version: mac OS mojave v10.14.6
* Link to your project: it one the tutorial

**Comment by Jakeeyturner** [comment]
Hi @makenoisewacamayo,

I'm going to close this as we currently have an issue open (and pinned) for it here - https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1621#issuecomment-552926559

We will fix this as soon as possible!

Thanks,
Jake
