### ISSUE TITLE
Failed to activate extension: Could not get electron verion, connect ECONNREFUSED 151.101.228.133:443

### ISSUE THREAD

**Issue by Linchengye** [IBM-Blockchain/blockchain-vscode-extension#1798]
## Description
I've already the needed version of node and npm using nvm. And I've also downgrade for vscode 1.39.2. But I got this error:  Failed to activate extension: Could not get electron verion, connect ECONNREFUSED 151.101.228.133:443. I have no idea why.

## Possible Fix
npm rebuild

## Log File
[1/3/2020 9:41:09 PM] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[1/3/2020 9:41:09 PM] [INFO] Starting IBM Blockchain Platform Extension
[1/3/2020 9:41:13 PM] [INFO] Attempting to require dependency: grpc
[1/3/2020 9:41:13 PM] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v69-linux-x64-glibc
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/lamsingjip/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.17/node_modules/grpc/src/node/extension_binary/node-v69-linux-x64-glibc/grpc_node.node'
[1/3/2020 9:41:16 PM] [ERROR] Failed to activate extension: Error: Could not get electron verion, connect ECONNREFUSED 151.101.228.133:443
[1/3/2020 9:41:16 PM] [ERROR] Error: Could not get electron verion, connect ECONNREFUSED 151.101.228.133:443
	at DependencyManager.<anonymous> (/home/lamsingjip/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.17/build/extension/dependencies/DependencyManager.js:569:23)
	at Generator.throw (<anonymous>)
	at rejected (/home/lamsingjip/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.17/build/extension/dependencies/DependencyManager.js:19:65)
	at process._tickCallback (internal/process/next_tick.js:68:7)

## Your Environment
* IBM Blockchain Platform Extension Version: 1.0.17
* Visual Studio Code version: 1.39.2
* Environment name and version: Node.js v8.17.0, npm v6.13.4
* Operating System and version: ubuntu 18.04

**Comment by devjue** [comment]
I think you're seeing some kind of network connection problem. You can see [here](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1607#issuecomment-549722548).
You can try to reach the following url: https://raw.githubusercontent.com/electron/releases/master/lite.json
If you can not reach it, that is the problem.

**Comment by Linchengye** [comment]
> I think you're seeing some kind of network connection problem. You can see [here](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1607#issuecomment-549722548).
> You can try to reach the following url: https://raw.githubusercontent.com/electron/releases/master/lite.json
> If you can not reach it, that is the problem.

Thanks! It's the network connection problem. I fixed it.
