### ISSUE TITLE
Failed to active extension

### ISSUE THREAD

**Issue by tujigogo** [IBM-Blockchain/blockchain-vscode-extension#1866]
Failed to activate extension: Failed to execute command "npm" with arguments "rebuild, grpc, --target=6.1.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1

MacOS 10.15.2
node version - 8.17.0
npm version -6.13.4

pls help....

**Comment by tujigogo** [comment]
By the way :
Could not rebuild native dependencies Failed to execute command "npm" with arguments "rebuild, grpc, --target=6.1.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

**Comment by cazfletch** [comment]
@tujigogo was there anymore info in the output view?

**Comment by tujigogo** [comment]
[2/4/2020 8:34:21 PM] [INFO] Tidying wallet, gateway, environment and repository settings
[2/4/2020 8:34:21 PM] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[2/4/2020 8:34:21 PM] [INFO] Starting IBM Blockchain Platform Extension
[2/4/2020 8:34:56 PM] [SUCCESS] Finished checking installed dependencies
[2/4/2020 8:35:04 PM] [INFO] Attempting to require dependency: grpc
[2/4/2020 8:35:04 PM] [INFO] Error requiring dependency: Failed to load /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node. Cannot find module '/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node'
Require stack:
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/grpc_extension.js
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/client_interceptors.js
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/client.js
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/index.js
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/build/extension/dependencies/DependencyManager.js
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/build/extension/webview/PreReqView.js
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/build/extension/util/ExtensionUtil.js
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/build/extension/util/Reporter.js
- /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/build/extension/extension.js
- /private/var/folders/1q/mtbfcwnx4415qbpnhnsdgvfm0000gn/T/AppTranslocation/D54BD6C2-1454-474F-BEFB-B2222504CAFC/d/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /private/var/folders/1q/mtbfcwnx4415qbpnhnsdgvfm0000gn/T/AppTranslocation/D54BD6C2-1454-474F-BEFB-B2222504CAFC/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /private/var/folders/1q/mtbfcwnx4415qbpnhnsdgvfm0000gn/T/AppTranslocation/D54BD6C2-1454-474F-BEFB-B2222504CAFC/d/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
[2/4/2020 8:35:04 PM] [INFO] Updating native node modules
[2/4/2020 8:35:04 PM] [INFO] Rebuilding native node modules
[2/4/2020 8:35:06 PM] [INFO] > grpc@1.23.3 install /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc
[2/4/2020 8:35:06 PM] [INFO] > node-pre-gyp install --fallback-to-build --library=static_library
[2/4/2020 8:35:06 PM] [INFO] node-pre-gyp
[2/4/2020 8:35:06 PM] [INFO]  WARN Using request for node-pre-gyp https download 
[2/4/2020 8:35:07 PM] [INFO] node-pre-gyp WARN
[2/4/2020 8:35:07 PM] [INFO]  Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.23.3/electron-v6.1-darwin-x64-unknown.tar.gz 
[2/4/2020 8:35:07 PM] [INFO] node-pre-gyp WARN Pre-built binaries not found for grpc@1.23.3 and electron@6.1.5 (electron-v6.1 ABI, unknown) (falling back to source compile with node-gyp) 
[2/4/2020 8:35:08 PM] [INFO] No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
[2/4/2020 8:35:08 PM] [INFO] No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
[2/4/2020 8:35:08 PM] [INFO] No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
[2/4/2020 8:35:08 PM] [INFO] gyp: No Xcode or CLT version detected!
[2/4/2020 8:35:08 PM] [INFO] gyp
[2/4/2020 8:35:08 PM] [INFO]  ERR! configure error 
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! stack Error: `gyp` failed with exit code: 1
[2/4/2020 8:35:08 PM] [INFO] gyp
[2/4/2020 8:35:08 PM] [INFO]  ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! stack     at emitTwo (events.js:126:13)
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! System Darwin 19.2.0
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v6.1" "--dist-url=https://atom.io/download/electron"
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! cwd /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! node -v v8.17.0
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! node-gyp -v v5.0.5
[2/4/2020 8:35:08 PM] [INFO] gyp ERR! not ok 
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! 
[2/4/2020 8:35:08 PM] [INFO] build error 
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! 
[2/4/2020 8:35:08 PM] [INFO] stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --dist-url=https://atom.io/download/electron' (1)
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! stack
[2/4/2020 8:35:08 PM] [INFO]      at emitTwo (events.js:126:13)
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! System Darwin 19.2.0
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR!
[2/4/2020 8:35:08 PM] [INFO]  command "/usr/local/bin/node" "/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! cwd /Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! node -v v8.17.0
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! node-pre-gyp -v v0.13.0
[2/4/2020 8:35:08 PM] [INFO] node-pre-gyp ERR! not ok 
[2/4/2020 8:35:08 PM] [INFO] Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/tujitongxue/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.18/node_modules/grpc/src/node/extension_binary/electron-v6.1-darwin-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --dist-url=https://atom.io/download/electron' (1)
[2/4/2020 8:35:08 PM] [INFO] npm
[2/4/2020 8:35:08 PM] [INFO]  ERR! code ELIFECYCLE
[2/4/2020 8:35:08 PM] [INFO] npm ERR! errno 1
[2/4/2020 8:35:08 PM] [INFO] npm ERR!
[2/4/2020 8:35:08 PM] [INFO]  grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
[2/4/2020 8:35:08 PM] [INFO] npm ERR! Exit status 1
[2/4/2020 8:35:08 PM] [INFO] npm ERR! 
[2/4/2020 8:35:08 PM] [INFO] npm ERR! Failed at the grpc@1.23.3 install script.
[2/4/2020 8:35:08 PM] [INFO] npm ERR!
[2/4/2020 8:35:08 PM] [INFO]  This is probably not a problem with npm. There is likely additional logging output above.
[2/4/2020 8:35:08 PM] [INFO] npm ERR! A complete log of this run can be found in:
[2/4/2020 8:35:08 PM] [INFO] npm ERR!     /Users/tujitongxue/.npm/_logs/2020-02-04T12_35_08_783Z-debug.log
[2/4/2020 8:35:08 PM] [ERROR] Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.5, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

**Comment by cazfletch** [comment]
From the error it looks like you don't have xcode installed `[2/4/2020 8:35:08 PM] [INFO] gyp: No Xcode or CLT version detected!`

It can be installed by running: `xcode-select --install`

And you can find which version you have by running: `xcode-select --version`

**Comment by tujigogo** [comment]
xcode-select version 2373.

**Comment by cazfletch** [comment]
have you definitely accepted the license you can accept by running `sudo xcodebuild -license`

**Comment by tujigogo** [comment]
Now it's running ... thx a  lot ....
