### ISSUE TITLE
Failed to activate extension:"Couldn't build native dependencies"

### ISSUE THREAD

**Issue by Sinha199** [IBM-Blockchain/blockchain-vscode-extension#2038]
Unable to activate the IBM Blockchain extension for Hyperledger Fabric 

## Description
 The more description is given in the log file

## Actual Behavior
Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.6, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

## Steps to Reproduce
[Blockchain.log file.txt](https://github.com/IBM-Blockchain/blockchain-vscode-extension/files/4308136/Blockchain.log.file.txt)

## Existing issues
 #1124  

## Log File
[9/3/2020 11:26:41 pm] [INFO] Updating native node modules
[9/3/2020 11:26:41 pm] [INFO] Rebuilding native node modules
[9/3/2020 11:26:58 pm] [INFO] > grpc@1.23.3 install C:\Users\anshu\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.21\node_modules\grpc
[9/3/2020 11:26:58 pm] [INFO] > node-pre-gyp install --fallback-to-build --library=static_library
[9/3/2020 11:27:01 pm] [INFO] node-pre-gyp
[9/3/2020 11:27:01 pm] [INFO]  
[9/3/2020 11:27:01 pm] [INFO] WARN Using request for node-pre-gyp https download 
[9/3/2020 11:27:23 pm] [INFO] node-pre-gyp
[9/3/2020 11:27:23 pm] [INFO]  WARN Pre-built binaries not installable for grpc@1.23.3 and electron@6.1.6 (electron-v6.1 ABI, unknown) (falling back to source compile with node-gyp) 
[9/3/2020 11:27:23 pm] [INFO] node-pre-gyp WARN Hit error connect ETIMEDOUT 104.28.22.74:443 
[9/3/2020 11:27:26 pm] [INFO] gyp
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] ERR! configure error
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] gyp
[9/3/2020 11:27:26 pm] [INFO]  ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
[9/3/2020 11:27:26 pm] [INFO] gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
[9/3/2020 11:27:26 pm] [INFO] gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
[9/3/2020 11:27:26 pm] [INFO] gyp 
[9/3/2020 11:27:26 pm] [INFO] ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
[9/3/2020 11:27:26 pm] [INFO] gyp ERR!
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] stack     at FSReqWrap.oncomplete (fs.js:152:21)
[9/3/2020 11:27:26 pm] [INFO] gyp
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] ERR!
[9/3/2020 11:27:26 pm] [INFO]  System Windows_NT 10.0.18362
[9/3/2020 11:27:26 pm] [INFO] gyp ERR!
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\anshu\\.vscode\\extensions\\ibmblockchain.ibm-blockchain-platform-1.0.21\\node_modules\\grpc\\src\\node\\extension_binary\\electron-v6.1-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\anshu\\.vscode\\extensions\\ibmblockchain.ibm-blockchain-platform-1.0.21\\node_modules\\grpc\\src\\node\\extension_binary\\electron-v6.1-win32-x64-unknown" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v6.1" "--dist-url=https://atom.io/download/electron"
[9/3/2020 11:27:26 pm] [INFO] gyp ERR! cwd C:\Users\anshu\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.21\node_modules\grpc
[9/3/2020 11:27:26 pm] [INFO] gyp ERR! node -v v8.14.0
[9/3/2020 11:27:26 pm] [INFO] gyp ERR! node-gyp -v v3.8.0
[9/3/2020 11:27:26 pm] [INFO] gyp ERR! not ok 
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp
[9/3/2020 11:27:26 pm] [INFO]  ERR! 
[9/3/2020 11:27:26 pm] [INFO] build error
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp
[9/3/2020 11:27:26 pm] [INFO]  ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\anshu\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.21\node_modules\grpc\src\node\extension_binary\electron-v6.1-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\anshu\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.21\node_modules\grpc\src\node\extension_binary\electron-v6.1-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --dist-url=https://atom.io/download/electron' (1)
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\anshu\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.21\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] ERR!
[9/3/2020 11:27:26 pm] [INFO]  System Windows_NT 10.0.18362
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp
[9/3/2020 11:27:26 pm] [INFO]  ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\anshu\\.vscode\\extensions\\ibmblockchain.ibm-blockchain-platform-1.0.21\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp
[9/3/2020 11:27:26 pm] [INFO]  ERR! cwd C:\Users\anshu\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.21\node_modules\grpc
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp ERR! node -v v8.14.0
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] ERR!
[9/3/2020 11:27:26 pm] [INFO]  node-pre-gyp -v
[9/3/2020 11:27:26 pm] [INFO]  v0.13.0
[9/3/2020 11:27:26 pm] [INFO] node-pre-gyp ERR! not ok
[9/3/2020 11:27:26 pm] [INFO]  
[9/3/2020 11:27:26 pm] [INFO] Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\anshu\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.21\node_modules\grpc\src\node\extension_binary\electron-v6.1-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\anshu\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.21\node_modules\grpc\src\node\extension_binary\electron-v6.1-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v6.1 --dist-url=https://atom.io/download/electron' (1)
[9/3/2020 11:27:26 pm] [INFO] npm
[9/3/2020 11:27:26 pm] [INFO]  ERR! code ELIFECYCLE
[9/3/2020 11:27:26 pm] [INFO] npm ERR! errno 1
[9/3/2020 11:27:26 pm] [INFO] npm ERR! grpc@1.23.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
[9/3/2020 11:27:26 pm] [INFO] npm ERR! Exit status 1
[9/3/2020 11:27:26 pm] [INFO] npm ERR! 
[9/3/2020 11:27:26 pm] [INFO] npm ERR! Failed at the grpc@1.23.3 install script.
[9/3/2020 11:27:26 pm] [INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[9/3/2020 11:27:26 pm] [INFO] npm ERR!
[9/3/2020 11:27:26 pm] [INFO]  A complete log of this run can be found in:
[9/3/2020 11:27:26 pm] [INFO] npm ERR!     C:\Users\anshu\AppData\Roaming\npm-cache\_logs\2020-03-09T17_57_26_502Z-debug.log
[9/3/2020 11:27:26 pm] [ERROR] Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=6.1.6, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

## Your Environment

* IBM Blockchain Platform Extension Version:v1.0.20
* Visual Studio Code version:1.42.1
c47d83b293181d9be64f27ff093689e8e7aed054
x64
* Node.js v8.14.0, npm v6.4.1
* Operating System and version:Windows 10 Pro ,10.0.18362 Build 18362

@cazfletch 
Please see to this.

**Comment by ishantheperson** [comment]
I am having a similar issue. When grpc it fails with this error:

```
[3/10/2020 9:15:43 PM] [INFO]   CXX(target) Release/obj.target/grpc_node/ext/call.o
[3/10/2020 9:15:43 PM] [INFO] ../ext/call.cc:104:53: error: no matching member function for call to 'Get'
[3/10/2020 9:15:43 PM] [INFO]     Local<String> current_key(Nan::To<String>(keys->Get(i)).ToLocalChecked());
[3/10/2020 9:15:43 PM] [INFO]                                               ~~~~~~^~~
[3/10/2020 9:15:43 PM] [INFO] /Users/ishan/Library/Caches/node-gyp/7.1.11/include/node/v8.h:3502:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
[3/10/2020 9:15:43 PM] [INFO]   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
[3/10/2020 9:15:43 PM] [INFO]                                           ^
[3/10/2020 9:15:43 PM] [INFO] /Users/ishan/Library/Caches/node-gyp/7.1.11/include/node/v8.h:3505:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
[3/10/2020 9:15:43 PM] [INFO]   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
```

This seems to be related to https://github.com/grpc/grpc-node/issues/1084

**Comment by ArnoldBraine** [comment]
If you check this thread https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues/1621 They almost have the same problem. They just advise to use another version of vscode, so i guess if you need it NOW, you should downgrade the version of vscode to 1.39, found here: https://code.visualstudio.com/updates/v1_39

**Comment by cazfletch** [comment]
closing as this will be fixed in the next release now we have updated to grpc 1.24.2
