### ISSUE TITLE
Version 1.0.24 Cann't  run

### ISSUE THREAD

**Issue by xiaomdong** [IBM-Blockchain/blockchain-vscode-extension#2097]
Version 1.0.24 Cann't  run in Ubuntu18.04.

## Description

After update the version to  1.0.24  in vscode 1.43.2 , the Fabric environment can't run.
I  teardown  and restart , It still doesn't work.
the logs :
[2020/3/28 上午11:26:56] [INFO] fatal: [localhost]: FAILED! => {"changed": false, "cmd": ["peer", "channel", "fetch", "config", "/tmp/ansible.nfer0ovn/config_block.pb", "-o", "localhost:17056", "-c", "testchainid", "--ordererTLSHostnameOverride", "orderer.example.com"], "delta": "0:00:03.475907", "end": "2020-03-28 03:26:56.552296", "msg": "non-zero return code", "rc": 1, "start": "2020-03-28 03:26:53.076389", "stderr": "Error: failed to create deliver client: orderer client failed to connect to localhost:17056: failed to create new connection: context deadline exceeded", "stderr_lines": ["Error: failed to create deliver client: orderer client failed to connect to localhost:17056: failed to create new connection: context deadline exceeded"], "stdout": "", "stdout_lines": []}
[2020/3/28 上午11:26:56] [INFO] PLAY RECAP *********************************************************************
[2020/3/28 上午11:26:56] [INFO] localhost                  : ok=143  changed=54   unreachable=0    failed=1    skipped=23   rescued=0    ignored=0   
[2020/3/28 上午11:27:55] [ERROR] Failed to start 1 Org Local Fabric: Error: Failed to execute command "/bin/sh" with  arguments "generate.sh" return code 2

the docker logs:
root@xd-ThinkCentre-M4600s-N000:/home/test# docker logs cda8a070fa85
2020-03-28 03:25:48.186 UTC [localconfig] completeInitialization -> INFO 001 Kafka.Version unset, setting to 0.10.2.0
2020-03-28 03:25:48.199 UTC [orderer.common.server] prettyPrintStruct -> INFO 002 Orderer config values:
	General.LedgerType = "file"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 17056
	General.TLS.Enabled = false
	General.TLS.PrivateKey = "/etc/hyperledger/fabric/tls/server.key"
	General.TLS.Certificate = "/etc/hyperledger/fabric/tls/server.crt"
	General.TLS.RootCAs = [/etc/hyperledger/fabric/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Cluster.ListenAddress = ""
	General.Cluster.ListenPort = 0
	General.Cluster.ServerCertificate = ""
	General.Cluster.ServerPrivateKey = ""
	General.Cluster.ClientCertificate = ""
	General.Cluster.ClientPrivateKey = ""
	General.Cluster.RootCAs = []
	General.Cluster.DialTimeout = 5s
	General.Cluster.RPCTimeout = 7s
	General.Cluster.ReplicationBufferSize = 20971520
	General.Cluster.ReplicationPullTimeout = 5s
	General.Cluster.ReplicationRetryTimeout = 5s
	General.Cluster.ReplicationBackgroundRefreshInterval = 5m0s
	General.Cluster.ReplicationMaxRetries = 12
	General.Cluster.SendBufferSize = 10
	General.Cluster.CertExpirationWarningThreshold = 168h0m0s
	General.Cluster.TLSHandshakeTimeShift = 0s
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.ConnectionTimeout = 0s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleInsecureSolo"
	General.SystemChannel = "testchainid"
	General.GenesisFile = "/var/hyperledger/production/genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LocalMSPDir = "/etc/hyperledger/fabric/msp"
	General.LocalMSPID = "OrdererMSP"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/etc/hyperledger/fabric/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.SwOpts.InmemKeystore =
	General.BCCSP.PluginOpts =
	General.Authentication.TimeWindow = 15m0s
	General.Authentication.NoExpirationChecks = false
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Kafka.SASLPlain.Enabled = false
	Kafka.SASLPlain.User = ""
	Kafka.SASLPlain.Password = ""
	Kafka.Topic.ReplicationFactor = 3
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
	Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
	Operations.ListenAddress = "0.0.0.0:17057"
	Operations.TLS.Enabled = false
	Operations.TLS.PrivateKey = "/etc/hyperledger/fabric/tls/server.key"
	Operations.TLS.Certificate = "/etc/hyperledger/fabric/tls/server.crt"
	Operations.TLS.RootCAs = []
	Operations.TLS.ClientAuthRequired = false
	Operations.TLS.ClientRootCAs = [/etc/hyperledger/fabric/tls/ca.crt]
	Metrics.Provider = "prometheus"
	Metrics.Statsd.Network = "udp"
	Metrics.Statsd.Address = "127.0.0.1:8125"
	Metrics.Statsd.WriteInterval = 30s
	Metrics.Statsd.Prefix = ""
panic: unable to bootstrap orderer. Error reading genesis block file: open /var/hyperledger/production/genesis.block: no such file or directory

goroutine 1 [running]:
github.com/hyperledger/fabric/orderer/common/bootstrap/file.(*fileBootstrapper).GenesisBlock(0xc00027ca40, 0xc00027ca40)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/bootstrap/file/bootstrap.go:39 +0x1c2
github.com/hyperledger/fabric/orderer/common/server.extractBootstrapBlock(0xc000018900, 0xf06)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:566 +0x21e
github.com/hyperledger/fabric/orderer/common/server.Start(0x1532c3e, 0x5, 0xc000018900)
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:96 +0x43
github.com/hyperledger/fabric/orderer/common/server.Main()
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/common/server/main.go:91 +0x208
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:15 +0x20
2020-03-28 03:26:50.305 UTC [localconfig] completeInitialization -> INFO 001 Kafka.Version unset, setting to 0.10.2.0
2020-03-28 03:26:50.316 UTC [orderer.common.server] prettyPrintStruct -> INFO 002 Orderer config values:
	General.LedgerType = "file"
	General.ListenAddress = "0.0.0.0"
	General.ListenPort = 17056
	General.TLS.Enabled = false
	General.TLS.PrivateKey = "/etc/hyperledger/fabric/tls/server.key"
	General.TLS.Certificate = "/etc/hyperledger/fabric/tls/server.crt"
	General.TLS.RootCAs = [/etc/hyperledger/fabric/tls/ca.crt]
	General.TLS.ClientAuthRequired = false
	General.TLS.ClientRootCAs = []
	General.Cluster.ListenAddress = ""
	General.Cluster.ListenPort = 0
	General.Cluster.ServerCertificate = ""
	General.Cluster.ServerPrivateKey = ""
	General.Cluster.ClientCertificate = ""
	General.Cluster.ClientPrivateKey = ""
	General.Cluster.RootCAs = []
	General.Cluster.DialTimeout = 5s
	General.Cluster.RPCTimeout = 7s
	General.Cluster.ReplicationBufferSize = 20971520
	General.Cluster.ReplicationPullTimeout = 5s
	General.Cluster.ReplicationRetryTimeout = 5s
	General.Cluster.ReplicationBackgroundRefreshInterval = 5m0s
	General.Cluster.ReplicationMaxRetries = 12
	General.Cluster.SendBufferSize = 10
	General.Cluster.CertExpirationWarningThreshold = 168h0m0s
	General.Cluster.TLSHandshakeTimeShift = 0s
	General.Keepalive.ServerMinInterval = 1m0s
	General.Keepalive.ServerInterval = 2h0m0s
	General.Keepalive.ServerTimeout = 20s
	General.ConnectionTimeout = 0s
	General.GenesisMethod = "file"
	General.GenesisProfile = "SampleInsecureSolo"
	General.SystemChannel = "testchainid"
	General.GenesisFile = "/var/hyperledger/production/genesis.block"
	General.Profile.Enabled = false
	General.Profile.Address = "0.0.0.0:6060"
	General.LocalMSPDir = "/etc/hyperledger/fabric/msp"
	General.LocalMSPID = "OrdererMSP"
	General.BCCSP.ProviderName = "SW"
	General.BCCSP.SwOpts.SecLevel = 256
	General.BCCSP.SwOpts.HashFamily = "SHA2"
	General.BCCSP.SwOpts.Ephemeral = false
	General.BCCSP.SwOpts.FileKeystore.KeyStorePath = "/etc/hyperledger/fabric/msp/keystore"
	General.BCCSP.SwOpts.DummyKeystore =
	General.BCCSP.SwOpts.InmemKeystore =
	General.BCCSP.PluginOpts =
	General.Authentication.TimeWindow = 15m0s
	General.Authentication.NoExpirationChecks = false
	FileLedger.Location = "/var/hyperledger/production/orderer"
	FileLedger.Prefix = "hyperledger-fabric-ordererledger"
	RAMLedger.HistorySize = 1000
	Kafka.Retry.ShortInterval = 5s
	Kafka.Retry.ShortTotal = 10m0s
	Kafka.Retry.LongInterval = 5m0s
	Kafka.Retry.LongTotal = 12h0m0s
	Kafka.Retry.NetworkTimeouts.DialTimeout = 10s
	Kafka.Retry.NetworkTimeouts.ReadTimeout = 10s
	Kafka.Retry.NetworkTimeouts.WriteTimeout = 10s
	Kafka.Retry.Metadata.RetryMax = 3
	Kafka.Retry.Metadata.RetryBackoff = 250ms
	Kafka.Retry.Producer.RetryMax = 3
	Kafka.Retry.Producer.RetryBackoff = 100ms
	Kafka.Retry.Consumer.RetryBackoff = 2s
	Kafka.Verbose = false
	Kafka.Version = 0.10.2.0
	Kafka.TLS.Enabled = false
	Kafka.TLS.PrivateKey = ""
	Kafka.TLS.Certificate = ""
	Kafka.TLS.RootCAs = []
	Kafka.TLS.ClientAuthRequired = false
	Kafka.TLS.ClientRootCAs = []
	Kafka.SASLPlain.Enabled = false
	Kafka.SASLPlain.User = ""
	Kafka.SASLPlain.Password = ""
	Kafka.Topic.ReplicationFactor = 3
	Debug.BroadcastTraceDir = ""
	Debug.DeliverTraceDir = ""
	Consensus = map[SnapDir:/var/hyperledger/production/orderer/etcdraft/snapshot WALDir:/var/hyperledger/production/orderer/etcdraft/wal]
	Operations.ListenAddress = "0.0.0.0:17057"
	Operations.TLS.Enabled = false
	Operations.TLS.PrivateKey = "/etc/hyperledger/fabric/tls/server.key"
	Operations.TLS.Certificate = "/etc/hyperledger/fabric/tls/server.crt"
	Operations.TLS.RootCAs = []
	Operations.TLS.ClientAuthRequired = false
	Operations.TLS.ClientRootCAs = [/etc/hyperledger/fabric/tls/ca.crt]
	Metrics.Provider = "prometheus"
	Metrics.Statsd.Network = "udp"
	Metrics.Statsd.Address = "127.0.0.1:8125"
	Metrics.Statsd.WriteInterval = 30s
	Metrics.Statsd.Prefix = ""
2020-03-28 03:26:51.720 UTC [orderer.common.server] extractSysChanLastConfig -> INFO 003 Bootstrapping because no existing channels
2020-03-28 03:26:51.722 UTC [fsblkstorage] newBlockfileMgr -> INFO 004 Getting block information from block storage
2020-03-28 03:26:52.469 UTC [orderer.commmon.multichannel] Initialize -> INFO 005 Starting system channel 'testchainid' with genesis block hash c21217a0640bc19e016523e5be44b298f3c4ee80defc0fc63cd826c60695a2fe and orderer type solo
2020-03-28 03:26:52.469 UTC [orderer.common.server] Start -> INFO 006 Starting orderer:
 Version: 1.4.6
 Commit SHA: 635fa7bc8
 Go version: go1.12.12
 OS/Arch: linux/amd64
2020-03-28 03:26:52.469 UTC [orderer.common.server] Start -> INFO 007 Beginning to serve requests

## My Environment

BM Blockchain Platform Extension Version: 1.0.24
Visual Studio Code version:1.43.2
Environment name and version:  Node.js v10.19.0, npm v6.13.4
Operating System and version: Ubuntu18.04.4

**Comment by xiaomdong** [comment]
If I disconnect my network from the Internet, The problem will be solved。
