### ISSUE TITLE
"Let's Blockchain" Issue

### ISSUE THREAD

**Issue by Malstre** [IBM-Blockchain/blockchain-vscode-extension#2408]
## Description

I installed the following prerequisites for the IBM Blockchain Platform installation:

- Node.js 10.20.1

- npm 6.14.4

- Docker 19.3.8

- Docker Compose 1.25.5

## Expected Behavior

I expected that it will launch the tutorial environment where I would begin the course.
## Actual Behavior

Instead I got an error message that states the following:
Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=7.2.4, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed

What should I do?

**Comment by Jakeeyturner** [comment]
Hi @Malstre,

Please could you post the rest of the logs from the 'Blockchain' output.

Thanks,
Jake

**Comment by Malstre** [comment]
Hi @Jakeeyturner,

I can't seem to find the logs from before, this is all I can show you. I also can't seem to find the installation requirements as well...

<img width="1339" alt="Screen Shot 2020-06-01 at 2 01 06 PM" src="https://user-images.githubusercontent.com/42371946/83454252-c8971d00-a410-11ea-871d-8f2db81151be.png">

**Comment by Jakeeyturner** [comment]
<img width="958" alt="Screenshot 2020-06-02 at 09 09 43" src="https://user-images.githubusercontent.com/10009752/83496445-0481bf00-a4b1-11ea-8c2a-522aeae39de4.png">

To get the logs, select 'Output' then click on the dropdown and select 'Blockchain'.

Thanks,
Jake

**Comment by Malstre** [comment]
Thanks @Jakeeyturner ,

Also here are the logs from the output from Blockchain:

[6/3/2020 8:34:13 PM] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[6/3/2020 8:34:13 PM] [INFO] Starting IBM Blockchain Platform Extension
[6/3/2020 8:34:17 PM] [INFO] Attempting to require dependency: grpc
[6/3/2020 8:34:17 PM] [INFO] Error requiring dependency: Failed to load /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/node/extension_binary/electron-v7.2-darwin-x64-unknown/grpc_node.node. Cannot find module '/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/node/extension_binary/electron-v7.2-darwin-x64-unknown/grpc_node.node'
Require stack:
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/grpc_extension.js
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/client_interceptors.js
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/client.js
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/index.js
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/build/extension/dependencies/DependencyManager.js
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/build/extension/webview/PreReqView.js
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/build/extension/util/ExtensionUtil.js
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/build/extension/util/Reporter.js
- /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/build/extension/extension.js
- /Users/malstre/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Users/malstre/Desktop/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Users/malstre/Desktop/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
[6/3/2020 8:34:17 PM] [INFO] Updating native node modules
[6/3/2020 8:34:17 PM] [INFO] Rebuilding native node modules
[6/3/2020 8:34:19 PM] [INFO] > grpc@1.24.2 install /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc
[6/3/2020 8:34:19 PM] [INFO] > node-pre-gyp install --fallback-to-build --library=static_library
[6/3/2020 8:34:20 PM] [INFO] node-pre-gyp
[6/3/2020 8:34:20 PM] [INFO]  WARN Using request for node-pre-gyp https download 
[6/3/2020 8:34:20 PM] [INFO] node-pre-gyp WARN
[6/3/2020 8:34:20 PM] [INFO]  Tried to download(404): https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/electron-v7.2-darwin-x64-unknown.tar.gz 
[6/3/2020 8:34:20 PM] [INFO] node-pre-gyp WARN Pre-built binaries not found for grpc@1.24.2 and electron@7.2.4 (electron-v7.2 ABI, unknown) (falling back to source compile with node-gyp) 
[6/3/2020 8:34:22 PM] [INFO] No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
[6/3/2020 8:34:22 PM] [INFO] No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
[6/3/2020 8:34:22 PM] [INFO] No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
[6/3/2020 8:34:22 PM] [INFO] gyp: No Xcode or CLT version detected!
[6/3/2020 8:34:22 PM] [INFO] gyp
[6/3/2020 8:34:22 PM] [INFO]  ERR! configure error 
[6/3/2020 8:34:22 PM] [INFO] gyp ERR!
[6/3/2020 8:34:22 PM] [INFO]  stack Error: `gyp` failed with exit code: 1
[6/3/2020 8:34:22 PM] [INFO] gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
[6/3/2020 8:34:22 PM] [INFO] gyp
[6/3/2020 8:34:22 PM] [INFO]  ERR! stack     at ChildProcess.emit (events.js:198:13)
[6/3/2020 8:34:22 PM] [INFO] gyp ERR! 
[6/3/2020 8:34:22 PM] [INFO] stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[6/3/2020 8:34:22 PM] [INFO] gyp ERR! System Darwin 19.5.0
[6/3/2020 8:34:22 PM] [INFO] gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/node/extension_binary/electron-v7.2-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/node/extension_binary/electron-v7.2-darwin-x64-unknown" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v7.2" "--dist-url=https://atom.io/download/electron"
[6/3/2020 8:34:22 PM] [INFO] gyp ERR! cwd /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc
[6/3/2020 8:34:22 PM] [INFO] gyp ERR! node -v v10.20.1
[6/3/2020 8:34:22 PM] [INFO] gyp ERR! node-gyp -v v5.1.0
[6/3/2020 8:34:22 PM] [INFO] gyp ERR! not ok 
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp
[6/3/2020 8:34:22 PM] [INFO]  ERR! build error 
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp
[6/3/2020 8:34:22 PM] [INFO]  ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/node/extension_binary/electron-v7.2-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/node/extension_binary/electron-v7.2-darwin-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v7.2 --dist-url=https://atom.io/download/electron' (1)
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! System Darwin 19.5.0
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! cwd /Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! node -v v10.20.1
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! node-pre-gyp -v v0.14.0
[6/3/2020 8:34:22 PM] [INFO] node-pre-gyp ERR! not ok 
[6/3/2020 8:34:22 PM] [INFO] Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/node/extension_binary/electron-v7.2-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/node_modules/grpc/src/node/extension_binary/electron-v7.2-darwin-x64-unknown --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v7.2 --dist-url=https://atom.io/download/electron' (1)
[6/3/2020 8:34:22 PM] [INFO] npm ERR! code ELIFECYCLE
[6/3/2020 8:34:22 PM] [INFO] npm ERR! 
[6/3/2020 8:34:22 PM] [INFO] errno 1
[6/3/2020 8:34:22 PM] [INFO] npm
[6/3/2020 8:34:22 PM] [INFO]  ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
[6/3/2020 8:34:22 PM] [INFO] npm ERR! Exit status 1
[6/3/2020 8:34:22 PM] [INFO] npm ERR! 
[6/3/2020 8:34:22 PM] [INFO] npm ERR! Failed at the grpc@1.24.2 install script.
[6/3/2020 8:34:22 PM] [INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[6/3/2020 8:34:22 PM] [INFO] npm ERR! A complete log of this run can be found in:
[6/3/2020 8:34:22 PM] [INFO] npm ERR!     /Users/malstre/.npm/_logs/2020-06-04T03_34_22_631Z-debug.log
[6/3/2020 8:34:22 PM] [ERROR] Could not rebuild native dependencies Failed to execute command "npm" with  arguments "rebuild, grpc, --target=7.2.4, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1. Please ensure that you have node and npm installed
[6/3/2020 8:34:22 PM] [ERROR] Failed to activate extension: Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=7.2.4, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
[6/3/2020 8:34:22 PM] [ERROR] Error: Failed to execute command "npm" with  arguments "rebuild, grpc, --target=7.2.4, --runtime=electron, --update-binary, --fallback-to-build, --target_arch=x64, --dist-url=https://atom.io/download/electron" return code 1
	at ChildProcess.<anonymous> (/Users/malstre/.vscode/extensions/ibmblockchain.ibm-blockchain-platform-1.0.31/build/extension/util/CommandUtil.js:76:39)
	at ChildProcess.emit (events.js:203:13)
	at ChildProcess.EventEmitter.emit (domain.js:476:20)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

**Comment by Jakeeyturner** [comment]
You need the Xcode command line tools, run this from your terminal and trying again:
`xcode-select --install`

Let me know what logs you see afterwards, thanks.

**Comment by Jakeeyturner** [comment]
I'm assuming that fixed the problem @Malstre  - closing the issue.

**Comment by Malstre** [comment]
Oh, not yet, I’ve been a bit busy lately. I’ll check it out by today. Sorry for the late response.


Sent from Yahoo Mail for iPhone


On Friday, June 12, 2020, 2:41 AM, Jake <notifications@github.com> wrote:




I'm assuming that fixed the problem @Malstre - closing the issue.

**Comment by Malstre** [comment]
Hi @Jakeeyturner, 

Trying to reinstall Xcode on my computer, but the app store says it can't be downloaded at this time. Is there another alternative or am I missing something that I don't see?

**Comment by Jakeeyturner** [comment]
@Malstre

Nope, just looks like you need to run `xcode-select --install`

Perhaps try again as the the download servers might have been having when you tried.

**Comment by Jakeeyturner** [comment]
Guessing this is working now - closing issue.
