### ISSUE TITLE
Local Fabric failed to start on Windows 10

### ISSUE THREAD

**Issue by charlesamie** [IBM-Blockchain/blockchain-vscode-extension#2409]
Trying to do course in IBM Blockchain platform and failing to connect to Fabric

In Windows Home

12:48:17 am] [INFO] IBM Blockchain Platform Extension activated
[1/6/2020 12:48:42 am] [INFO] connecting to fabric environment
[1/6/2020 12:48:43 am] [INFO] startFabricRuntime
[1/6/2020 12:48:44 am] [INFO] C:\Users\charles\.fabric-vscode\environments\1 Org Local Fabric>
[1/6/2020 12:48:44 am] [INFO] rem
[1/6/2020 12:48:44 am] [INFO] C:\Users\charles\.fabric-vscode\environments\1 Org Local Fabric>rem Copyright IBM Corp All Rights Reserved 
[1/6/2020 12:48:44 am] [INFO] C:\Users\charles\.fabric-vscode\environments\1 Org Local Fabric>rem
[1/6/2020 12:48:44 am] [INFO] C:\Users\charles\.fabric-vscode\environments\1 Org Local Fabric>rem SPDX-License-Identifier: Apache-2.0 
[1/6/2020 12:48:44 am] [INFO] C:\Users\charles\.fabric-vscode\environments\1 Org Local Fabric>rem
[1/6/2020 12:48:44 am] [INFO] C:\Users\charles\.fabric-vscode\environments\1 Org Local Fabric>docker run --rm -v "C:\Users\charles\.fabric-vscode\environments\1 Org Local Fabric":/network -v /var/run/docker.sock:/var/run/docker.sock --network host ibmblockchain/vscode-prereqs:0.0.16 ansible-playbook /network/playbook.yml 
[1/6/2020 12:48:45 am] [INFO] docker: Error response from daemon: invalid mode: /network.
[1/6/2020 12:48:45 am] [INFO] See 'docker run --help'.
[1/6/2020 12:48:45 am] [INFO] C:\Users\charles\.fabric-vscode\environments\1 Org Local Fabric>if 125 NEQ 0 (exit /b 125 ) 
[1/6/2020 12:48:45 am] [ERROR] Failed to start 1 Org Local Fabric: Error: Failed to execute command "cmd" with  arguments "/c, generate.cmd" return code 125
Can you please help to resolve this issue.

**Comment by Jakeeyturner** [comment]
Hi,

As our [dependencies](https://github.com/IBM-Blockchain/blockchain-vscode-extension#additional-requirements-for-windows) state, you need to be using Windows 10 Pro or Enterprise and have the Anniversary Update 1607.
Unfortunately Windows Home is not supported.

Thanks,
Jake

**Comment by charlesamie** [comment]
Hi Jake
Is there alternative option since I have only Windows home laptop?

**Comment by Jakeeyturner** [comment]
Hey @charlesamie,

If your computer specs are good enough, you could create an Ubuntu VM and use that instead.

Thanks,
Jake

**Comment by charlesamie** [comment]
Hi Jake
I tried in different laptop with Windows 10 Pro still getting other errors as shown below.  Can you kindly assist to resolve.Still couldnt pass pre requisites in IBM Block Chain Platform Extension

Docker version 19.03.8, build afacb8b  (Getting error Enable Hyper-v, tried still no luck) 
![VS error](https://user-images.githubusercontent.com/44497082/83898102-134bc880-a774-11ea-95bb-585b510ec0dd.PNG)



Node v8.17.0
NPM 6.13.4

/2020 8:43:24 PM] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[6/5/2020 8:43:25 PM] [INFO] Starting IBM Blockchain Platform Extension
[6/5/2020 8:43:25 PM] [INFO] Attempting to require dependency: grpc
[6/5/2020 8:43:27 PM] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v7.2-win32-x64-unknown
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\node\extension_binary\electron-v7.2-win32-x64-unknown\grpc_node.node'
Require stack:
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\grpc_extension.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\client_interceptors.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\client.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\index.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\webview\PreReqView.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\ExtensionUtil.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\Reporter.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\extension.js
- c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
[6/5/2020 8:43:27 PM] [INFO] Updating native node modules
[6/5/2020 8:43:27 PM] [INFO] Rebuilding native node modules
[6/5/2020 8:43:27 PM] [ERROR] Could not rebuild native dependencies spawn UNKNOWN. Please ensure that you have node and npm installed
[6/5/2020 8:43:27 PM] [ERROR] Failed to activate extension: Error: spawn UNKNOWN
[6/5/2020 8:43:27 PM] [ERROR] Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:553:9)
	at Function.<anonymous> (c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\CommandUtil.js:62:41)
	at Generator.next (<anonymous>)
	at c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\CommandUtil.js:21:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\CommandUtil.js:17:12)
	at Function.sendCommandWithOutput (c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\CommandUtil.js:53:16)
	at DependencyManager.<anonymous> (c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js:495:57)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js:18:58)
[6/5/2020 8:44:50 PM] [INFO] Attempting to require dependency: grpc
[6/5/2020 8:44:51 PM] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v7.2-win32-x64-unknown
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\node\extension_binary\electron-v7.2-win32-x64-unknown\grpc_node.node'
Require stack:
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\grpc_extension.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\client_interceptors.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\client.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\index.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\webview\PreReqView.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\ExtensionUtil.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\Reporter.js
- c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\extension.js
- c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
[6/5/2020 8:44:51 PM] [INFO] Updating native node modules
[6/5/2020 8:44:51 PM] [INFO] Rebuilding native node modules
[6/5/2020 8:44:51 PM] [ERROR] Could not rebuild native dependencies spawn UNKNOWN. Please ensure that you have node and npm installed
[6/5/2020 9:24:02 PM] [SUCCESS] Finished checking installed dependencies
