### ISSUE TITLE
Could not rebuild native dependencies spawn UNKNOWN. Please ensure that you have node and npm installed

### ISSUE THREAD

**Issue by charlesamie** [IBM-Blockchain/blockchain-vscode-extension#2444]
I tried in  laptop with Windows 10 Pro still getting other errors as shown below. Can you kindly assist to resolve.Still couldnt pass pre requisites in IBM Block Chain Platform Extension

Docker version 19.03.8, build afacb8b (Getting error Enable Hyper-v, tried still no luck)
VS error

Node v8.17.0
NPM 6.13.4
![VS error](https://user-images.githubusercontent.com/44497082/83998472-51b4d380-a97e-11ea-83b0-7249033a3008.PNG)

/2020 8:43:24 PM] [IMPORTANT] Log files can be found by running the Developer: Open Logs Folder command from the palette

[6/5/2020 8:43:25 PM] [INFO] Starting IBM Blockchain Platform Extension
[6/5/2020 8:43:25 PM] [INFO] Attempting to require dependency: grpc
[6/5/2020 8:43:27 PM] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v7.2-win32-x64-unknown
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\node\extension_binary\electron-v7.2-win32-x64-unknown\grpc_node.node'
Require stack:

c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\grpc_extension.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\client_interceptors.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\client.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\index.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\webview\PreReqView.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\ExtensionUtil.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\Reporter.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\extension.js
c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
[6/5/2020 8:43:27 PM] [INFO] Updating native node modules
[6/5/2020 8:43:27 PM] [INFO] Rebuilding native node modules
[6/5/2020 8:43:27 PM] [ERROR] Could not rebuild native dependencies spawn UNKNOWN. Please ensure that you have node and npm installed
[6/5/2020 8:43:27 PM] [ERROR] Failed to activate extension: Error: spawn UNKNOWN
[6/5/2020 8:43:27 PM] [ERROR] Error: spawn UNKNOWN
at ChildProcess.spawn (internal/child_process.js:394:11)
at Object.spawn (child_process.js:553:9)
at Function. (c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\CommandUtil.js:62:41)
at Generator.next ()
at c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\CommandUtil.js:21:71
at new Promise ()
at __awaiter (c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\CommandUtil.js:17:12)
at Function.sendCommandWithOutput (c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\CommandUtil.js:53:16)
at DependencyManager. (c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js:495:57)
at Generator.next ()
at fulfilled (c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js:18:58)
[6/5/2020 8:44:50 PM] [INFO] Attempting to require dependency: grpc
[6/5/2020 8:44:51 PM] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v7.2-win32-x64-unknown
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\node\extension_binary\electron-v7.2-win32-x64-unknown\grpc_node.node'
Require stack:
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\grpc_extension.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\client_interceptors.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\client.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\index.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\webview\PreReqView.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\ExtensionUtil.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\util\Reporter.js
c:\Users\charles.p.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\extension.js
c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
c:\Users\charles.p\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
[6/5/2020 8:44:51 PM] [INFO] Updating native node modules
[6/5/2020 8:44:51 PM] [INFO] Rebuilding native node modules
[6/5/2020 8:44:51 PM] [ERROR] Could not rebuild native dependencies spawn UNKNOWN. Please ensure that you have node and npm installed
[6/5/2020 9:24:02 PM] [SUCCESS] Finished checking installed dependencies

**Comment by Jakeeyturner** [comment]
Hi @charlesamie,

What commands did you run to install Node & npm / how did you install it?

**Comment by charlesamie** [comment]
Hi Jake
I installed below versions in Windows 10 Pro using respective MSI

Node v8.17.0
NPM 6.13.4

Also for Docker I am getting error to enable Hyper-V which I did still no luck:(
Still pre perquisites keep on poping up as shown.

**Comment by Jakeeyturner** [comment]
Strange, it doesn't seem like our extension can find/use your Node/npm instance.
Did you add Node to the PATH variable?

It's worth noting that you will need Hyper-V working in order for Docker to work on Windows.

**Comment by charlesamie** [comment]
Is there any stable IBM Blockchain platform which works perfectly for Windows 10 Pro since I'm facing odd issues for last 2 weeks on every pre requisite softwares?

**Comment by Jakeeyturner** [comment]
All versions of the extension use the same code to check that it can access the required prerequisites. 

In order to get you moving forward, I would recommend installing Ubuntu in a VM on your machine and using the extension inside of that.

**Comment by charlesamie** [comment]
Hey Jake
I tried Ubuntu in my other laptop but it didnt even launch due to low memory and Disk space.Is there anything I can do with Windows?

**Comment by charlesamie** [comment]
[6/8/2020 7:22:21 PM] [IMPORTANT] Log files can be found by running the `Developer: Open Logs Folder` command from the palette

[6/8/2020 7:22:21 PM] [INFO] Starting IBM Blockchain Platform Extension
[6/8/2020 7:22:21 PM] [INFO] Attempting to require dependency: grpc
[6/8/2020 7:22:22 PM] [INFO] Error requiring dependency: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v69-win32-x64-unknown
Found: [node-v64-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module 'c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\node_modules\grpc\src\node\extension_binary\node-v69-win32-x64-unknown\grpc_node.node'
[6/8/2020 7:22:23 PM] [ERROR] Failed to activate extension: Error: Could not get electron version, Request failed with status code 407
[6/8/2020 7:22:23 PM] [ERROR] Error: Could not get electron version, Request failed with status code 407
	at DependencyManager.<anonymous> (c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js:583:23)
	at Generator.throw (<anonymous>)
	at rejected (c:\Users\charles.p\.vscode\extensions\ibmblockchain.ibm-blockchain-platform-1.0.32\build\extension\dependencies\DependencyManager.js:19:65)
	at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Jakeeyturner** [comment]
If you can't run a VM then you'll need to try and sort out your dependencies. 

What do you get when you run `where node` from your terminal, and also, what is the value of your PATH environment variable?

**Comment by charlesamie** [comment]
C:\Program Files\nodejs\node.exe

**Comment by Jakeeyturner** [comment]
@charlesamie what's the value of your PATH environment variable?

**Comment by charlesamie** [comment]
![Env variables](https://user-images.githubusercontent.com/44497082/84574391-c2675000-adc3-11ea-9ecd-921137a4f9f9.PNG)

**Comment by Jakeeyturner** [comment]
Closing - `Failed to load gRPC binary module ` error is no longer a problem with latest version.
